# Generated by Django 5.2.1 on 2025-05-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('campervan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.campervan')),
            ],
        ),
    ]
