# Generated by Django 5.2.1 on 2025-05-20 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_seasonalrate_booking_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampervanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('campervan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.campervan')),
            ],
        ),
    ]
