# Generated by Django 5.2.1 on 2025-05-20 12:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_campervanimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campervanimage',
            name='url',
        ),
        migrations.AddField(
            model_name='campervanimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
