# Generated by Django 5.2.1 on 2025-05-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_campervan_description_de_campervan_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_has_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_over_21',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='rentals.additionalservice'),
        ),
    ]
