# Generated by Django 5.2.1 on 2025-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_additionalservice_booking_additional_driver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
