# Generated by Django 5.2.1 on 2025-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_invoice_booking_additional_driver_license_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campervan',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='seasonalrate',
            name='end',
        ),
        migrations.RemoveField(
            model_name='seasonalrate',
            name='start',
        ),
        migrations.AddField(
            model_name='seasonalrate',
            name='end_day',
            field=models.PositiveSmallIntegerField(default=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonalrate',
            name='end_month',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonalrate',
            name='start_day',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonalrate',
            name='start_month',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
