# Generated by Django 5.2.1 on 2025-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_remove_campervan_price_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_driver_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='additional_driver_license_document',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='additional_driver_license_expiry',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='additional_driver_license_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='additional_insurance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='primary_driver_address_manual',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_driver_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_driver_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_driver_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_driver_street_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_driver_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
