# Generated by Django 5.2.1 on 2025-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_remove_booking_additional_driver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='primary_driver_street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
