# Generated by Django 5.2.1 on 2025-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_booking_deposit_hidden_booking_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
    ]
