# Generated by Django 5.2.1 on 2025-07-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_invoice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('phone_contact', models.CharField(blank=True, max_length=30)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('windshields', models.TextField(blank=True)),
                ('paintwork', models.TextField(blank=True)),
                ('bodywork', models.TextField(blank=True)),
                ('tires_front', models.TextField(blank=True)),
                ('tires_rear', models.TextField(blank=True)),
                ('seats', models.TextField(blank=True)),
                ('upholstery', models.TextField(blank=True)),
                ('windows', models.TextField(blank=True)),
                ('lights', models.TextField(blank=True)),
                ('flooring', models.TextField(blank=True)),
                ('known_damage', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='rentals.booking')),
            ],
        ),
        migrations.CreateModel(
            name='HandoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='handover_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rentals.handoverchecklist')),
            ],
        ),
    ]
