# Generated by Django 5.2.1 on 2025-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_handoverchecklist_customer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Customer Signature'),
        ),
    ]
