# Generated by Django 5.2.1 on 2025-07-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_booking_customer_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverchecklist',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_checklists', to='rentals.booking'),
        ),
        migrations.CreateModel(
            name='ReturnChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('phone_contact', models.CharField(blank=True, max_length=30)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('windshields', models.TextField(blank=True)),
                ('paintwork', models.TextField(blank=True)),
                ('bodywork', models.TextField(blank=True)),
                ('tires_front', models.TextField(blank=True)),
                ('tires_rear', models.TextField(blank=True)),
                ('seats', models.TextField(blank=True)),
                ('upholstery', models.TextField(blank=True)),
                ('windows', models.TextField(blank=True)),
                ('lights', models.TextField(blank=True)),
                ('flooring', models.TextField(blank=True)),
                ('known_damage', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_checklists', to='rentals.booking')),
            ],
        ),
    ]
