# Generated by Django 5.2.1 on 2025-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_alter_handoverchecklist_booking_returnchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverchecklist',
            name='bodywork',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='flooring',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='lights',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='paintwork',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='seats',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='tires_front',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='tires_rear',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='upholstery',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='windows',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='handoverchecklist',
            name='windshields',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='bodywork',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='flooring',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='lights',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='paintwork',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='seats',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='tires_front',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='tires_rear',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='upholstery',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='windows',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnchecklist',
            name='windshields',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=10),
        ),
    ]
