# Generated by Django 5.2.1 on 2025-07-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_alter_handoverchecklist_bodywork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_checklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_booking', to='rentals.handoverchecklist'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_checklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_booking', to='rentals.handoverchecklist'),
        ),
        migrations.DeleteModel(
            name='ReturnChecklist',
        ),
    ]
