# Generated by Django 5.2.1 on 2025-07-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_booking_pickup_checklist_booking_return_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverchecklist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='handoverphoto',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.handoverchecklist'),
        ),
    ]
