# Generated by Django 5.2.1 on 2025-08-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0023_carouselimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
