# Generated by Django 5.2.1 on 2025-08-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0026_delete_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
