# Generated by Django 5.2.1 on 2025-08-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0027_blockeddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeddate',
            options={'ordering': ['start_date'], 'verbose_name': 'Dates Booked', 'verbose_name_plural': 'Dates Booked'},
        ),
    ]
