# Generated by Django 5.2.1 on 2025-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0029_booking_vat_amount_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
