# Generated by Django 5.2.1 on 2025-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0030_alter_booking_vat_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vat_amount',
        ),
    ]
