# Generated by Django 5.2.1 on 2025-09-01 15:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0031_remove_booking_vat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverchecklist',
            name='customer_signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='signature'),
        ),
    ]
