# Generated by Django 5.2.1 on 2025-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0032_alter_handoverchecklist_customer_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverchecklist',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
