# Generated by Django 5.2.1 on 2025-05-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_campingdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='campingdestination',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campingdestination',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
