# Generated by Django 5.2.1 on 2025-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_campingdestination_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingdestination',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
