# Generated by Django 5.2.1 on 2025-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_campingdestination_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingdestination',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
