# Generated by Django 5.2.1 on 2025-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_discountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='amount',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount to apply, e.g., 10 for 10%', max_digits=5),
            preserve_default=False,
        ),
    ]
